<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Icon Picker - Curated Icon Sets
    |--------------------------------------------------------------------------
    |
    | Categorised icons from FontAwesome and RPGAwesome for use in the
    | icon picker component on maps, timelines, and other entities.
    |
    */

    'categories' => [

        'fantasy' => [
            'label' => 'icons.categories.fantasy',
            'icons' => [
                'fa-solid fa-hat-wizard',
                'fa-solid fa-wand-sparkles',
                'fa-solid fa-wand-magic-sparkles',
                'fa-solid fa-book-skull',
                'fa-solid fa-scroll',
                'fa-solid fa-fire',
                'fa-solid fa-fire-flame-curved',
                'fa-solid fa-bolt',
                'fa-solid fa-ghost',
                'fa-solid fa-skull',
                'fa-solid fa-skull-crossbones',
                'fa-solid fa-dragon',
                'fa-solid fa-shield-halved',
                'fa-solid fa-shield',
                'fa-solid fa-crown',
                'fa-solid fa-gem',
                'fa-solid fa-ring',
                'fa-solid fa-hand-sparkles',
                'fa-solid fa-hand-fist',
                'fa-solid fa-book-open',
                'fa-solid fa-book',
                'fa-solid fa-feather',
                'fa-solid fa-feather-pointed',
                'fa-solid fa-flask',
                'fa-solid fa-vial',
                'fa-solid fa-mortar-pestle',
                'fa-solid fa-broom',
                'fa-solid fa-spider',
                'fa-solid fa-cat',
                'fa-solid fa-dove',
                'fa-solid fa-horse',
                'fa-solid fa-horse-head',
                'fa-solid fa-otter',
                'fa-solid fa-paw',
                'fa-solid fa-wolf-pack-battalion',
                'fa-solid fa-dungeon',
                'fa-solid fa-chess-rook',
                'fa-solid fa-chess-knight',
                'fa-solid fa-chess-queen',
                'fa-solid fa-chess-king',
            ],
        ],

        'rpg' => [
            'label' => 'icons.categories.rpg',
            'icons' => [
                'ra ra-sword',
                'ra ra-crossed-swords',
                'ra ra-axe',
                'ra ra-battered-axe',
                'ra ra-large-hammer',
                'ra ra-daggers',
                'ra ra-plain-dagger',
                'ra ra-rune-sword',
                'ra ra-broadhead-arrow',
                'ra ra-archer',
                'ra ra-crossbow',
                'ra ra-shield',
                'ra ra-round-shield',
                'ra ra-heavy-shield',
                'ra ra-helmet',
                'ra ra-knight-helmet',
                'ra ra-crowned-heart',
                'ra ra-gem-pendant',
                'ra ra-gem',
                'ra ra-crown',
                'ra ra-crystal-ball',
                'ra ra-fairy-wand',
                'ra ra-scroll-unfurled',
                'ra ra-book',
                'ra ra-quill-ink',
                'ra ra-potion',
                'ra ra-health-decrease',
                'ra ra-health',
                'ra ra-lightning-bolt',
                'ra ra-fire',
                'ra ra-ice-shield',
                'ra ra-explosion',
                'ra ra-aura',
                'ra ra-sun',
                'ra ra-moon-sun',
                'ra ra-eye-monster',
                'ra ra-dragon',
                'ra ra-hydra',
                'ra ra-wolf-howl',
                'ra ra-bat-sword',
                'ra ra-spider-face',
                'ra ra-death-skull',
                'ra ra-skull',
                'ra ra-tombstone',
                'ra ra-coffin',
                'ra ra-hand',
                'ra ra-hearts',
                'ra ra-trumpet',
                'ra ra-tower',
                'ra ra-castle-flag',
                'ra ra-capitol',
                'ra ra-anvil',
                'ra ra-forging',
                'ra ra-key',
                'ra ra-key-basic',
                'ra ra-locked-chest',
                'ra ra-gold-bar',
                'ra ra-coins',
                'ra ra-perspective-dice-one',
                'ra ra-perspective-dice-six',
            ],
        ],

        'maps' => [
            'label' => 'icons.categories.maps',
            'icons' => [
                'fa-solid fa-map-pin',
                'fa-solid fa-location-dot',
                'fa-solid fa-location-crosshairs',
                'fa-solid fa-compass',
                'fa-solid fa-map',
                'fa-solid fa-map-location-dot',
                'fa-solid fa-mountain',
                'fa-solid fa-mountain-sun',
                'fa-solid fa-mountain-city',
                'fa-solid fa-tree',
                'fa-solid fa-tree-city',
                'fa-solid fa-water',
                'fa-solid fa-anchor',
                'fa-solid fa-ship',
                'fa-solid fa-sailboat',
                'fa-solid fa-bridge',
                'fa-solid fa-bridge-water',
                'fa-solid fa-road',
                'fa-solid fa-route',
                'fa-solid fa-signs-post',
                'fa-solid fa-archway',
                'fa-solid fa-torii-gate',
                'fa-solid fa-monument',
                'fa-solid fa-landmark',
                'fa-solid fa-building-columns',
                'fa-solid fa-city',
                'fa-solid fa-house',
                'fa-solid fa-house-chimney',
                'fa-solid fa-church',
                'fa-solid fa-place-of-worship',
                'fa-solid fa-shop',
                'fa-solid fa-tent',
                'fa-solid fa-campground',
                'fa-solid fa-warehouse',
                'fa-solid fa-industry',
                'fa-solid fa-igloo',
                'fa-solid fa-gopuram',
                'fa-solid fa-vihara',
                'fa-solid fa-kaaba',
            ],
        ],

        'people' => [
            'label' => 'icons.categories.people',
            'icons' => [
                'fa-solid fa-user',
                'fa-solid fa-user-secret',
                'fa-solid fa-user-shield',
                'fa-solid fa-user-ninja',
                'fa-solid fa-user-tie',
                'fa-solid fa-users',
                'fa-solid fa-people-group',
                'fa-solid fa-person',
                'fa-solid fa-person-walking',
                'fa-solid fa-person-running',
                'fa-solid fa-person-rifle',
                'fa-solid fa-children',
                'fa-solid fa-baby',
                'fa-solid fa-skull',
                'fa-solid fa-cross',
                'fa-solid fa-heart',
                'fa-solid fa-brain',
                'fa-solid fa-eye',
                'fa-solid fa-hand',
                'fa-solid fa-handshake',
            ],
        ],

        'symbols' => [
            'label' => 'icons.categories.symbols',
            'icons' => [
                'fa-solid fa-star',
                'fa-solid fa-circle',
                'fa-solid fa-square',
                'fa-solid fa-diamond',
                'fa-solid fa-bookmark',
                'fa-solid fa-flag',
                'fa-solid fa-banner',
                'fa-solid fa-certificate',
                'fa-solid fa-award',
                'fa-solid fa-medal',
                'fa-solid fa-trophy',
                'fa-solid fa-sun',
                'fa-solid fa-moon',
                'fa-solid fa-cloud',
                'fa-solid fa-snowflake',
                'fa-solid fa-leaf',
                'fa-solid fa-clover',
                'fa-solid fa-seedling',
                'fa-solid fa-yin-yang',
                'fa-solid fa-om',
                'fa-solid fa-peace',
                'fa-solid fa-ankh',
                'fa-solid fa-cross',
                'fa-solid fa-star-of-david',
                'fa-solid fa-star-and-crescent',
                'fa-solid fa-infinity',
                'fa-solid fa-question',
                'fa-solid fa-exclamation',
                'fa-solid fa-circle-info',
                'fa-solid fa-triangle-exclamation',
                'fa-solid fa-circle-check',
                'fa-solid fa-circle-xmark',
                'fa-solid fa-lock',
                'fa-solid fa-key',
                'fa-solid fa-bell',
                'fa-solid fa-hourglass-half',
                'fa-solid fa-clock',
            ],
        ],

        'objects' => [
            'label' => 'icons.categories.objects',
            'icons' => [
                'fa-solid fa-coins',
                'fa-solid fa-money-bill',
                'fa-solid fa-sack-dollar',
                'fa-solid fa-scale-balanced',
                'fa-solid fa-gavel',
                'fa-solid fa-hammer',
                'fa-solid fa-wrench',
                'fa-solid fa-screwdriver-wrench',
                'fa-solid fa-gear',
                'fa-solid fa-gears',
                'fa-solid fa-compass-drafting',
                'fa-solid fa-ruler',
                'fa-solid fa-magnifying-glass',
                'fa-solid fa-binoculars',
                'fa-solid fa-glasses',
                'fa-solid fa-utensils',
                'fa-solid fa-wine-glass',
                'fa-solid fa-beer-mug-empty',
                'fa-solid fa-mug-hot',
                'fa-solid fa-jar',
                'fa-solid fa-basket-shopping',
                'fa-solid fa-box',
                'fa-solid fa-suitcase',
                'fa-solid fa-scroll',
                'fa-solid fa-envelope',
                'fa-solid fa-pen',
                'fa-solid fa-pen-fancy',
                'fa-solid fa-paintbrush',
                'fa-solid fa-palette',
                'fa-solid fa-music',
                'fa-solid fa-guitar',
                'fa-solid fa-drum',
            ],
        ],
    ],
];
